"?column?"
"INSERT INTO questions (id, question_text) VALUES (1, 'Com que frequência você lê livros?');"
"INSERT INTO questions (id, question_text) VALUES (2, 'Quanto tempo você costuma ter para ler por dia?');"
"INSERT INTO questions (id, question_text) VALUES (3, 'Você prefere histórias com muitas páginas ou poucas?');"
"INSERT INTO questions (id, question_text) VALUES (4, 'Que tipo de história você mais gosta?');"
"INSERT INTO questions (id, question_text) VALUES (5, 'Você prefere histórias que acontecem:');"
"INSERT INTO questions (id, question_text) VALUES (6, 'Qual dessas histórias parece mais interessante?');"
"INSERT INTO questions (id, question_text) VALUES (7, 'Qual tipo de filme você mais gosta?');"
"INSERT INTO questions (id, question_text) VALUES (8, 'Você gosta de histórias com:');"
"INSERT INTO questions (id, question_text) VALUES (9, 'Você prefere personagens:');"
"INSERT INTO questions (id, question_text) VALUES (10, 'Você prefere histórias:');"
"INSERT INTO questions (id, question_text) VALUES (11, 'Você gosta de histórias baseadas em:');"
"INSERT INTO questions (id, question_text) VALUES (12, 'Você prefere ler:');"
"INSERT INTO questions (id, question_text) VALUES (13, 'Você já leu algum desses tipos de livro?');"
"INSERT INTO questions (id, question_text) VALUES (14, 'Você gosta de histórias que:');"
"INSERT INTO questions (id, question_text) VALUES (15, 'Você gostaria que sua próxima leitura fosse:');"
