"?column?"
"INSERT INTO options (id, question_id, option_text) VALUES (1, 1, 'Nunca li um livro completo');"
"INSERT INTO options (id, question_id, option_text) VALUES (2, 1, 'Leio raramente');"
"INSERT INTO options (id, question_id, option_text) VALUES (3, 1, 'Leio às vezes');"
"INSERT INTO options (id, question_id, option_text) VALUES (4, 1, 'Leio com frequência');"
"INSERT INTO options (id, question_id, option_text) VALUES (5, 2, 'Menos de 10 minutos');"
"INSERT INTO options (id, question_id, option_text) VALUES (6, 2, 'Entre 10 e 20 minutos');"
"INSERT INTO options (id, question_id, option_text) VALUES (7, 2, 'Mais de 30 minutos');"
"INSERT INTO options (id, question_id, option_text) VALUES (8, 3, 'Poucas páginas');"
"INSERT INTO options (id, question_id, option_text) VALUES (9, 3, 'Médio');"
"INSERT INTO options (id, question_id, option_text) VALUES (10, 3, 'Muitas páginas');"
"INSERT INTO options (id, question_id, option_text) VALUES (11, 4, 'Fantasia');"
"INSERT INTO options (id, question_id, option_text) VALUES (12, 4, 'Romance');"
"INSERT INTO options (id, question_id, option_text) VALUES (13, 4, 'Mistério');"
"INSERT INTO options (id, question_id, option_text) VALUES (14, 4, 'Aventura');"
"INSERT INTO options (id, question_id, option_text) VALUES (15, 4, 'Terror');"
"INSERT INTO options (id, question_id, option_text) VALUES (16, 4, 'Ficção científica');"
"INSERT INTO options (id, question_id, option_text) VALUES (17, 5, 'Em mundos mágicos');"
"INSERT INTO options (id, question_id, option_text) VALUES (18, 5, 'No mundo real');"
"INSERT INTO options (id, question_id, option_text) VALUES (19, 5, 'No futuro');"
"INSERT INTO options (id, question_id, option_text) VALUES (20, 6, 'Um detetive resolvendo um crime');"
"INSERT INTO options (id, question_id, option_text) VALUES (21, 6, 'Uma jornada perigosa');"
"INSERT INTO options (id, question_id, option_text) VALUES (22, 6, 'Um amor inesperado');"
"INSERT INTO options (id, question_id, option_text) VALUES (23, 6, 'Um segredo assustador');"
"INSERT INTO options (id, question_id, option_text) VALUES (24, 7, 'Ação');"
"INSERT INTO options (id, question_id, option_text) VALUES (25, 7, 'Romance');"
"INSERT INTO options (id, question_id, option_text) VALUES (26, 7, 'Suspense');"
"INSERT INTO options (id, question_id, option_text) VALUES (27, 7, 'Fantasia');"
"INSERT INTO options (id, question_id, option_text) VALUES (28, 8, 'Dragões ou magia');"
"INSERT INTO options (id, question_id, option_text) VALUES (29, 8, 'Robôs ou tecnologia');"
"INSERT INTO options (id, question_id, option_text) VALUES (30, 8, 'Pessoas comuns');"
"INSERT INTO options (id, question_id, option_text) VALUES (31, 9, 'Jovens como você');"
"INSERT INTO options (id, question_id, option_text) VALUES (32, 9, 'Adultos');"
"INSERT INTO options (id, question_id, option_text) VALUES (33, 10, 'Engraçadas');"
"INSERT INTO options (id, question_id, option_text) VALUES (34, 10, 'Emocionantes');"
"INSERT INTO options (id, question_id, option_text) VALUES (35, 10, 'Cheias de ação');"
"INSERT INTO options (id, question_id, option_text) VALUES (36, 11, 'Fatos reais');"
"INSERT INTO options (id, question_id, option_text) VALUES (37, 11, 'Imaginação');"
"INSERT INTO options (id, question_id, option_text) VALUES (38, 12, 'Histórias rápidas');"
"INSERT INTO options (id, question_id, option_text) VALUES (39, 12, 'Histórias detalhadas');"
"INSERT INTO options (id, question_id, option_text) VALUES (40, 13, 'HQ ou quadrinhos');"
"INSERT INTO options (id, question_id, option_text) VALUES (41, 13, 'Mangá');"
"INSERT INTO options (id, question_id, option_text) VALUES (42, 13, 'Romance');"
"INSERT INTO options (id, question_id, option_text) VALUES (43, 13, 'Nunca li');"
"INSERT INTO options (id, question_id, option_text) VALUES (44, 14, 'Dão medo');"
"INSERT INTO options (id, question_id, option_text) VALUES (45, 14, 'Fazem rir');"
"INSERT INTO options (id, question_id, option_text) VALUES (46, 14, 'Fazem pensar');"
"INSERT INTO options (id, question_id, option_text) VALUES (47, 15, 'Fácil');"
"INSERT INTO options (id, question_id, option_text) VALUES (48, 15, 'Desafiadora');"
