"?column?"
"INSERT INTO books (id, title, author, description) VALUES (1, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Um garoto descobre que é um bruxo e começa sua jornada em Hogwarts.');"
"INSERT INTO books (id, title, author, description) VALUES (2, 'Percy Jackson e o Ladrão de Raios', 'Rick Riordan', 'Um garoto descobre que é filho de um deus grego.');"
"INSERT INTO books (id, title, author, description) VALUES (3, 'Jogos Vorazes', 'Suzanne Collins', 'Uma jovem luta pela sobrevivência em uma competição mortal.');"
"INSERT INTO books (id, title, author, description) VALUES (4, 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Uma história filosófica sobre amizade e imaginação.');"
"INSERT INTO books (id, title, author, description) VALUES (5, 'Diário de um Banana', 'Jeff Kinney', 'Um garoto registra suas aventuras engraçadas no colégio.');"
"INSERT INTO books (id, title, author, description) VALUES (6, 'A Seleção', 'Kiera Cass', 'Uma jovem participa de um concurso para se tornar princesa.');"
"INSERT INTO books (id, title, author, description) VALUES (7, 'Extraordinário', 'R.J. Palacio', 'Um garoto com aparência diferente enfrenta desafios escolares.');"
"INSERT INTO books (id, title, author, description) VALUES (8, 'Maze Runner', 'James Dashner', 'Um grupo de jovens tenta escapar de um labirinto mortal.');"
"INSERT INTO books (id, title, author, description) VALUES (9, 'Coraline', 'Neil Gaiman', 'Uma garota descobre um mundo assustador por trás de uma porta.');"
"INSERT INTO books (id, title, author, description) VALUES (10, 'As Crônicas de Nárnia', 'C.S. Lewis', 'Crianças entram em um mundo mágico cheio de aventuras.');"
"INSERT INTO books (id, title, author, description) VALUES (11, 'Cidade de Papel', 'John Green', 'Um jovem embarca em uma jornada para encontrar uma garota misteriosa.');"
"INSERT INTO books (id, title, author, description) VALUES (12, 'A Culpa é das Estrelas', 'John Green', 'Dois jovens se apaixonam enquanto enfrentam doenças.');"
"INSERT INTO books (id, title, author, description) VALUES (13, 'O Hobbit', 'J.R.R. Tolkien', 'Um hobbit embarca em uma aventura épica.');"
"INSERT INTO books (id, title, author, description) VALUES (14, 'A Menina que Roubava Livros', 'Markus Zusak', 'Uma jovem descobre o poder das palavras durante a guerra.');"
"INSERT INTO books (id, title, author, description) VALUES (15, 'Os Karas', 'Pedro Bandeira', 'Um grupo de jovens resolve mistérios intrigantes.');"
"INSERT INTO books (id, title, author, description) VALUES (16, 'Turma da Mônica Jovem', 'Mauricio de Sousa', 'Histórias divertidas em estilo mangá.');"
"INSERT INTO books (id, title, author, description) VALUES (17, 'Naruto', 'Masashi Kishimoto', 'Um jovem ninja busca reconhecimento e amizade.');"
"INSERT INTO books (id, title, author, description) VALUES (18, 'Death Note', 'Tsugumi Ohba', 'Um estudante encontra um caderno capaz de matar pessoas.');"
"INSERT INTO books (id, title, author, description) VALUES (19, 'O Ladrão de Raios', 'Rick Riordan', 'Primeira aventura de Percy Jackson.');"
"INSERT INTO books (id, title, author, description) VALUES (20, 'Dom Casmurro (adaptação juvenil)', 'Machado de Assis', 'Uma versão adaptada do clássico brasileiro.');"
